### ISSUE TITLE
Fix Z constraint violation during simulation

### ISSUE THREAD

**Issue by larsvanhout** [benGmaker/4GB20-Group-4#24]
After running the simulation for a while, the error which mentions that the Z constraints are violated appears.  That is the moment that the simulation stops.  Often times this is after the movement of picking up a bolt (from what was seen in the simulation).  This was something that was not yet resolved, and it might be because of some issues in the trajectory planning.

**Comment by Farming13** [comment]
SSA12 Allard

**Comment by Farming13** [comment]
Done
